version: '3'

services:
    sensor-controller:
        build: sensor-controller/
        ports:
            - "80:80"
        depends_on:
            - mosquitto
    homeassistant:
        build: hass/
        restart: always
        volumes:
            - hass-config:/config
        ports:
            - "8123:8123"
        depends_on:
            - mosquitto
    mosquitto:
        build: mosquitto/
        restart: always
        volumes:
            - mosquitto-data:/mosquitto/data
            - mosquitto-log:/mosquitto/log
        ports:
            - "1883:1883"
            - "9001:9001"

volumes:
    mosquitto-data:
    mosquitto-log:
    hass-config: