name: Java CI with Gradle

on:
  push:
    branches:
      - master
      - feature/*
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      name: Cache gradle dependencies
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run gradle build
      run: ./gradlew build
      
  deploy: 
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      name: Cache gradle dependencies
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        name: deploy_id_rsa
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Deploy master
      run: ./gradlew deploy -Pserver.dev.host=$DEV_HOST -Pserver.dev.user=$DEV_USER -Pserver.dev.identity_file=~/.ssh/deploy_id_rsa -Pdeploy.allowAnyHosts
      env:
        DEV_HOST: ${{ secrets.DEV_HOST }}
        DEV_USER: ${{ secrets.DEV_USER }}
